// Danh sách đề bài hợp lệ. Mỗi "id" PHẢI khớp đúng tên thư mục trong
// tests/{id}/ của repo backend (grading-engine).
//
// "language" PHẢI khớp đúng với "language" khai báo trong
// tests/{id}/config.json ở repo backend - nếu lệch nhau, sinh viên sẽ nộp
// nhầm loại file (main.c / main.cpp) và bị báo lỗi biên dịch.
//   - "c"   -> sinh viên nộp file .c, biên dịch bằng gcc
//   - "cpp" -> sinh viên nộp file .cpp, biên dịch bằng g++
//
// Khi thêm đề bài mới:
//   1. Tạo thư mục tests/{id}/ trong repo grading-engine với các cặp file
//      N.in / N.out và config.json (xem README của repo backend).
//   2. Thêm một dòng vào mảng bên dưới với đúng "language".
export const PROBLEMS = [
  // --- PART 1: BASICS & CONDITIONALS (001 - 010) ---
  { id: "001_sum_two_numbers", label: "001. Sum of two numbers (C)", language: "c" },
  { id: "001_sum_two_numbers_cpp", label: "001. Sum of two numbers (C++)", language: "cpp" },
  { id: "002_cal_two_numbers", label: "002. Calculate two numbers (C)", language: "c" },
  { id: "002_cal_two_numbers_cpp", label: "002. Calculate two numbers (C++)", language: "cpp" },
  { id: "003_cuuchuong", label: "003. Multiplication table (C)", language: "c" },
  { id: "003_cuuchuong_cpp", label: "003. Multiplication table (C++)", language: "cpp" },
  { id: "004_findmax", label: "004. Find maximum value (C)", language: "c" },
  { id: "004_findmax_cpp", label: "004. Find maximum value (C++)", language: "cpp" },
  { id: "005_check_sign", label: "005. Check positive, negative, or zero (C)", language: "c" },
  { id: "005_check_sign_cpp", label: "005. Check positive, negative, or zero (C++)", language: "cpp" },
  { id: "006_even_odd", label: "006. Even or odd number (C)", language: "c" },
  { id: "006_even_odd_cpp", label: "006. Even or odd number (C++)", language: "cpp" },
  { id: "007_score_pass_fail", label: "007. Score pass or fail (C)", language: "c" },
  { id: "007_score_pass_fail_cpp", label: "007. Score pass or fail (C++)", language: "cpp" },
  { id: "008_score_classification", label: "008. Score classification (C)", language: "c" },
  { id: "008_score_classification_cpp", label: "008. Score classification (C++)", language: "cpp" },
  { id: "009_leap_year", label: "009. Leap year check (C)", language: "c" },
  { id: "009_leap_year_cpp", label: "009. Leap year check (C++)", language: "cpp" },
  { id: "010_university_admission", label: "010. University admission eligibility (C)", language: "c" },
  { id: "010_university_admission_cpp", label: "010. University admission eligibility (C++)", language: "cpp" },

  // --- PART 2: SWITCH-CASE & MENU-DRIVEN (011 - 018) ---
  { id: "011_day_of_week", label: "011. Day of the week (C)", language: "c" },
  { id: "011_day_of_week_cpp", label: "011. Day of the week (C++)", language: "cpp" },
  { id: "012_simple_calculator", label: "012. Simple calculator (C)", language: "c" },
  { id: "012_simple_calculator_cpp", label: "012. Simple calculator (C++)", language: "cpp" },
  { id: "013_month_info", label: "013. Month information (C)", language: "c" },
  { id: "013_month_info_cpp", label: "013. Month information (C++)", language: "cpp" },
  { id: "014_traffic_light", label: "014. Traffic light controller (C)", language: "c" },
  { id: "014_traffic_light_cpp", label: "014. Traffic light controller (C++)", language: "cpp" },
  { id: "015_unit_converter", label: "015. Menu unit converter (C)", language: "c" },
  { id: "015_unit_converter_cpp", label: "015. Menu unit converter (C++)", language: "cpp" },
  { id: "016_atm_menu", label: "016. ATM menu simulation (C)", language: "c" },
  { id: "016_atm_menu_cpp", label: "016. ATM menu simulation (C++)", language: "cpp" },
  { id: "017_coffee_shop", label: "017. Coffee shop order (C)", language: "c" },
  { id: "017_coffee_shop_cpp", label: "017. Coffee shop order (C++)", language: "cpp" },
  { id: "018_mobile_plan", label: "018. Mobile phone plan (C)", language: "c" },
  { id: "018_mobile_plan_cpp", label: "018. Mobile phone plan (C++)", language: "cpp" },

  // --- PART 3: FOR LOOPS & BASIC ITERATION (019 - 028) ---
  { id: "019_range_numbers", label: "019. Display numbers in a range (C)", language: "c" },
  { id: "019_range_numbers_cpp", label: "019. Display numbers in a range (C++)", language: "cpp" },
  { id: "020_reverse_numbers", label: "020. Display numbers in reverse order (C)", language: "c" },
  { id: "020_reverse_numbers_cpp", label: "020. Display numbers in reverse order (C++)", language: "cpp" },
  { id: "021_sum_1_to_n", label: "021. Calculate sum from 1 to N (C)", language: "c" },
  { id: "021_sum_1_to_n_cpp", label: "021. Calculate sum from 1 to N (C++)", language: "cpp" },
  { id: "022_product_1_to_n", label: "022. Calculate product from 1 to N (C)", language: "c" },
  { id: "022_product_1_to_n_cpp", label: "022. Calculate product from 1 to N (C++)", language: "cpp" },
  { id: "023_multiples_of_n", label: "023. Display multiples of a number (C)", language: "c" },
  { id: "023_multiples_of_n_cpp", label: "023. Display multiples of a number (C++)", language: "cpp" },
  { id: "024_sum_even_numbers", label: "024. Calculate sum of even numbers (C)", language: "c" },
  { id: "024_sum_even_numbers_cpp", label: "024. Calculate sum of even numbers (C++)", language: "cpp" },
  { id: "025_count_digits", label: "025. Count digits of an integer (C)", language: "c" },
  { id: "025_count_digits_cpp", label: "025. Count digits of an integer (C++)", language: "cpp" },
  { id: "026_average_n_numbers", label: "026. Calculate average of N numbers (C)", language: "c" },
  { id: "026_average_n_numbers_cpp", label: "026. Calculate average of N numbers (C++)", language: "cpp" },
  { id: "027_min_max_n_numbers", label: "027. Find minimum and maximum (C)", language: "c" },
  { id: "027_min_max_n_numbers_cpp", label: "027. Find minimum and maximum (C++)", language: "cpp" },
  { id: "028_number_pattern", label: "028. Generate a number pattern (C)", language: "c" },
  { id: "028_number_pattern_cpp", label: "028. Generate a number pattern (C++)", language: "cpp" },

  // --- PART 4: ADVANCED LOOPS & PRIME/MATH ALGORITHMS (029 - 037) ---
  { id: "029_odd_numbers_range", label: "029. Print odd numbers in a range (C)", language: "c" },
  { id: "029_odd_numbers_range_cpp", label: "029. Print odd numbers in a range (C++)", language: "cpp" },
  { id: "030_sum_of_squares", label: "030. Calculate sum of squares (C)", language: "c" },
  { id: "030_sum_of_squares_cpp", label: "030. Calculate sum of squares (C++)", language: "cpp" },
  { id: "031_power_without_pow", label: "031. Calculate power x^n (C)", language: "c" },
  { id: "031_power_without_pow_cpp", label: "031. Calculate power x^n (C++)", language: "cpp" },
  { id: "032_count_divisible_by_3", label: "032. Count numbers divisible by 3 (C)", language: "c" },
  { id: "032_count_divisible_by_3_cpp", label: "032. Count numbers divisible by 3 (C++)", language: "cpp" },
  { id: "033_reverse_number", label: "033. Reverse a number (C)", language: "c" },
  { id: "033_reverse_number_cpp", label: "033. Reverse a number (C++)", language: "cpp" },
  { id: "034_check_prime", label: "034. Check whether a number is prime (C)", language: "c" },
  { id: "034_check_prime_cpp", label: "034. Check whether a number is prime (C++)", language: "cpp" },
  { id: "035_primes_in_range", label: "035. Display prime numbers in a range (C)", language: "c" },
  { id: "035_primes_in_range_cpp", label: "035. Display prime numbers in a range (C++)", language: "cpp" },
  { id: "036_fibonacci_sequence", label: "036. Fibonacci sequence (C)", language: "c" },
  { id: "036_fibonacci_sequence_cpp", label: "036. Fibonacci sequence (C++)", language: "cpp" },
  { id: "037_number_pyramid", label: "037. Number pyramid pattern (C)", language: "c" },
  { id: "037_number_pyramid_cpp", label: "037. Number pyramid pattern (C++)", language: "cpp" },

  // --- PART 5: 1D ARRAYS & ARRAY ALGORITHMS (038 - 047) ---
  { id: "038_array_even_positions", label: "038. Display elements at even positions (C)", language: "c" },
  { id: "038_array_even_positions_cpp", label: "038. Display elements at even positions (C++)", language: "cpp" },
  { id: "039_array_sum_odd_positions", label: "039. Calculate sum at odd positions (C)", language: "c" },
  { id: "039_array_sum_odd_positions_cpp", label: "039. Calculate sum at odd positions (C++)", language: "cpp" },
  { id: "040_array_replace_negatives", label: "040. Replace negative values with zero (C)", language: "c" },
  { id: "040_array_replace_negatives_cpp", label: "040. Replace negative values with zero (C++)", language: "cpp" },
  { id: "041_array_first_occurrence", label: "041. Find first occurrence of value (C)", language: "c" },
  { id: "041_array_first_occurrence_cpp", label: "041. Find first occurrence of value (C++)", language: "cpp" },
  { id: "042_array_last_occurrence", label: "042. Find last occurrence of value (C)", language: "c" },
  { id: "042_array_last_occurrence_cpp", label: "042. Find last occurrence of value (C++)", language: "cpp" },
  { id: "043_array_count_occurrences", label: "043. Count occurrences of value (C)", language: "c" },
  { id: "043_array_count_occurrences_cpp", label: "043. Count occurrences of value (C++)", language: "cpp" },
  { id: "044_array_remove_value", label: "044. Remove all occurrences of value (C)", language: "c" },
  { id: "044_array_remove_value_cpp", label: "044. Remove all occurrences of value (C++)", language: "cpp" },
  { id: "045_array_insert_element", label: "045. Insert an element into array (C)", language: "c" },
  { id: "045_array_insert_element_cpp", label: "045. Insert an element into array (C++)", language: "cpp" },
  { id: "046_array_delete_position", label: "046. Delete element at position (C)", language: "c" },
  { id: "046_array_delete_position_cpp", label: "046. Delete element at position (C++)", language: "cpp" },
  { id: "047_array_rotate_right", label: "047. Rotate array to the right (C)", language: "c" },
  { id: "047_array_rotate_right_cpp", label: "047. Rotate array to the right (C++)", language: "cpp" },

  // --- PART 6: 2D ARRAYS & MATRIX OPERATIONS (048 - 057) ---
  { id: "048_matrix_display_columns", label: "048. Display matrix by columns (C)", language: "c" },
  { id: "048_matrix_display_columns_cpp", label: "048. Display matrix by columns (C++)", language: "cpp" },
  { id: "049_matrix_row_sum", label: "049. Calculate sum of each row (C)", language: "c" },
  { id: "049_matrix_row_sum_cpp", label: "049. Calculate sum of each row (C++)", language: "cpp" },
  { id: "050_matrix_col_product", label: "050. Calculate product of each column (C)", language: "c" },
  { id: "050_matrix_col_product_cpp", label: "050. Calculate product of each column (C++)", language: "cpp" },
  { id: "051_matrix_find_positions", label: "051. Find position of a value (C)", language: "c" },
  { id: "051_matrix_find_positions_cpp", label: "051. Find position of a value (C++)", language: "cpp" },
  { id: "052_matrix_count_zeros", label: "052. Count zero elements in matrix (C)", language: "c" },
  { id: "052_matrix_count_zeros_cpp", label: "052. Count zero elements in matrix (C++)", language: "cpp" },
  { id: "053_matrix_max_each_col", label: "053. Find largest element in each column (C)", language: "c" },
  { id: "053_matrix_max_each_col_cpp", label: "053. Find largest element in each column (C++)", language: "cpp" },
  { id: "054_matrix_main_diagonal_prod", label: "054. Main diagonal product (C)", language: "c" },
  { id: "054_matrix_main_diagonal_prod_cpp", label: "054. Main diagonal product (C++)", language: "cpp" },
  { id: "055_matrix_sec_diagonal_sum", label: "055. Secondary diagonal sum (C)", language: "c" },
  { id: "055_matrix_sec_diagonal_sum_cpp", label: "055. Secondary diagonal sum (C++)", language: "cpp" },
  { id: "056_matrix_transpose", label: "056. Transpose a matrix (C)", language: "c" },
  { id: "056_matrix_transpose_cpp", label: "056. Transpose a matrix (C++)", language: "cpp" },
  { id: "057_matrix_multiplication", label: "057. Matrix multiplication (C)", language: "c" },
  { id: "057_matrix_multiplication_cpp", label: "057. Matrix multiplication (C++)", language: "cpp" },

  // --- PART 7: STRINGS & STRING ALGORITHMS (058 - 067) ---
  { id: "058_string_count_upper_lower", label: "058. Count upper and lower chars (C)", language: "c" },
  { id: "058_string_count_upper_lower_cpp", label: "058. Count upper and lower chars (C++)", language: "cpp" },
  { id: "059_string_remove_spaces", label: "059. Remove all spaces from string (C)", language: "c" },
  { id: "059_string_remove_spaces_cpp", label: "059. Remove all spaces from string (C++)", language: "cpp" },
  { id: "060_string_replace_char", label: "060. Replace a character in string (C)", language: "c" },
  { id: "060_string_replace_char_cpp", label: "060. Replace a character in string (C++)", language: "cpp" },
  { id: "061_string_count_words", label: "061. Count words in a sentence (C)", language: "c" },
  { id: "061_string_count_words_cpp", label: "061. Count words in a sentence (C++)", language: "cpp" },
  { id: "062_string_first_word", label: "062. Extract the first word (C)", language: "c" },
  { id: "062_string_first_word_cpp", label: "062. Extract the first word (C++)", language: "cpp" },
  { id: "063_string_longest_word", label: "063. Find the longest word (C)", language: "c" },
  { id: "063_string_longest_word_cpp", label: "063. Find the longest word (C++)", language: "cpp" },
  { id: "064_string_to_uppercase", label: "064. Convert string to uppercase (C)", language: "c" },
  { id: "064_string_to_uppercase_cpp", label: "064. Convert string to uppercase (C++)", language: "cpp" },
  { id: "065_string_remove_consecutive_dup", label: "065. Remove consecutive duplicate chars (C)", language: "c" },
  { id: "065_string_remove_consecutive_dup_cpp", label: "065. Remove consecutive duplicate chars (C++)", language: "cpp" },
  { id: "066_string_check_anagram", label: "066. Check whether two strings are anagrams (C)", language: "c" },
  { id: "066_string_check_anagram_cpp", label: "066. Check whether two strings are anagrams (C++)", language: "cpp" },
  { id: "067_string_run_length_compression", label: "067. Run-length string compression (C)", language: "c" },
  { id: "067_string_run_length_compression_cpp", label: "067. Run-length string compression (C++)", language: "cpp" },

  // --- PART 8: 2D STRINGS & ARRAYS OF STRINGS (068 - 077) ---
  { id: "068_string_array_reverse_order", label: "068. Display strings in reverse order (C)", language: "c" },
  { id: "068_string_array_reverse_order_cpp", label: "068. Display strings in reverse order (C++)", language: "cpp" },
  { id: "069_string_array_shortest", label: "069. Find the shortest string (C)", language: "c" },
  { id: "069_string_array_shortest_cpp", label: "069. Find the shortest string (C++)", language: "cpp" },
  { id: "070_string_array_count_prefix", label: "070. Count strings starting with char (C)", language: "c" },
  { id: "070_string_array_count_prefix_cpp", label: "070. Count strings starting with char (C++)", language: "cpp" },
  { id: "071_string_array_search", label: "071. Search for a string in array (C)", language: "c" },
  { id: "071_string_array_search_cpp", label: "071. Search for a string in array (C++)", language: "cpp" },
  { id: "072_string_array_count_substring", label: "072. Count strings containing substring (C)", language: "c" },
  { id: "072_string_array_count_substring_cpp", label: "072. Count strings containing substring (C++)", language: "cpp" },
  { id: "073_string_array_length_filter", label: "073. Display strings with specific length (C)", language: "c" },
  { id: "073_string_array_length_filter_cpp", label: "073. Display strings with specific length (C++)", language: "cpp" },
  { id: "074_string_array_to_uppercase", label: "074. Convert all strings to uppercase (C)", language: "c" },
  { id: "074_string_array_to_uppercase_cpp", label: "074. Convert all strings to uppercase (C++)", language: "cpp" },
  { id: "075_string_array_sort_by_length", label: "075. Sort strings by length (C)", language: "c" },
  { id: "075_string_array_sort_by_length_cpp", label: "075. Sort strings by length (C++)", language: "cpp" },
  { id: "076_string_array_most_frequent", label: "076. Find most frequent string (C)", language: "c" },
  { id: "076_string_array_most_frequent_cpp", label: "076. Find most frequent string (C++)", language: "cpp" },
  { id: "077_string_array_group_by_first_char", label: "077. Group strings by first character (C)", language: "c" },
  { id: "077_string_array_group_by_first_char_cpp", label: "077. Group strings by first character (C++)", language: "cpp" },

  // --- PART 9: STRUCTURES & STRUCT ARRAYS (078 - 087) ---
  { id: "078_struct_book_info", label: "078. Book information (C)", language: "c" },
  { id: "078_struct_book_info_cpp", label: "078. Book information (C++)", language: "cpp" },
  { id: "079_struct_employee_salary", label: "079. Employee salary calculation (C)", language: "c" },
  { id: "079_struct_employee_salary_cpp", label: "079. Employee salary calculation (C++)", language: "cpp" },
  { id: "080_struct_product_inventory", label: "080. Product inventory value (C)", language: "c" },
  { id: "080_struct_product_inventory_cpp", label: "080. Product inventory value (C++)", language: "cpp" },
  { id: "081_struct_time_duration", label: "081. Time duration addition (C)", language: "c" },
  { id: "081_struct_time_duration_cpp", label: "081. Time duration addition (C++)", language: "cpp" },
  { id: "082_struct_rectangle_calc", label: "082. Rectangle calculations (C)", language: "c" },
  { id: "082_struct_rectangle_calc_cpp", label: "082. Rectangle calculations (C++)", language: "cpp" },
  { id: "083_struct_array_books_filter", label: "083. Array of books filter (C)", language: "c" },
  { id: "083_struct_array_books_filter_cpp", label: "083. Array of books filter (C++)", language: "cpp" },
  { id: "084_struct_oldest_person", label: "084. Find the oldest person (C)", language: "c" },
  { id: "084_struct_oldest_person_cpp", label: "084. Find the oldest person (C++)", language: "cpp" },
  { id: "085_struct_student_ranking", label: "085. Student ranking by average (C)", language: "c" },
  { id: "085_struct_student_ranking_cpp", label: "085. Student ranking by average (C++)", language: "cpp" },
  { id: "086_struct_bank_account", label: "086. Bank account deposit management (C)", language: "c" },
  { id: "086_struct_bank_account_cpp", label: "086. Bank account deposit management (C++)", language: "cpp" },
  { id: "087_struct_employee_management", label: "087. Employee management & search (C)", language: "c" },
  { id: "087_struct_employee_management_cpp", label: "087. Employee management & search (C++)", language: "cpp" },
];
